static/css/hugo-academic.css

I used two figures with captions, and the result was two "FIGURE 1" labels.
This patch resets the counter, so that it works for siblings.

Create captions counter on body to prevent reset at every figaction

---

exampleSite/config.toml

Format the comments in the file `config.toml` so that the maximum width
per line is 80 characters.
(BTW: Thanks for this awesome theme. I want to use it for redesigning http://kulla.me :smile: )

config.toml: Format comments.

---

layouts/partials/widgets/about.html

See commit messages for more details...

Improvement for social icons in about.html

---

layouts/partials/header.html

Use the always available `.Site.RSSLink` as default RSS feed.

header.html: Add .Site.RSSLink as default RSS feed.

---

layouts/partials/footer.html

License: MIT
Signed-off-by: Stephan Kulla <git.mail@kulla.me>

vim footer.html: Shorten if condition for MathJAX

---

layouts/partials/footer.html
layouts/partials/header.html
layouts/partials/navbar.html

Use the Hugo function `relURL` in order to make URLs relative. See also https://github.com/gcushen/hugo-academic/pull/33#issuecomment-247333203 for more details.

Use Hugo function `relURL`

---

layouts/partials/footer_container.html

Apply aria-hidden to the whole span which contains the back to top span.

footer: Apply aria-hidden to whole button.

---

exampleSite/content/home/publications.md
exampleSite/content/home/publications_selected.md
layouts/index.html
layouts/partials/widgets/about.html
layouts/partials/widgets/contact.html
layouts/partials/widgets/custom.html

Replace the long if-else block in index.html with a direct inclusion of
the widgets.

widgets: Direct inclusion of widgets

---

layouts/partials/widgets/about.html

This PR is ahead of PR #45... Main change: https://github.com/gcushen/hugo-academic/commit/b20e5f9d8ce07137f7b8ddb448a902107e2f86c8

about.html: Make avatar choosable

---

layouts/partials/widgets/contact.html

Base on #45. Additional Commit: https://github.com/gcushen/hugo-academic/commit/c08ffc5fce2256d39dd7fa3502aae63beb8e8fd8

contact.html: Shorten code for autolinks

---

layouts/partials/widgets/about.html

Base on #45. Main commit: https://github.com/gcushen/hugo-academic/commit/d637b6e07abbeee0a648aff56f9003225398ddf6

about.html: Trim long line for social icons

---

exampleSite/config.toml
layouts/partials/widgets/contact.html

Hello.
I think it would be nice to add [Telegram](https://telegram.org/) username and link to Contacts widget.
Best regards.

Add Telegram contact.

---

i18n/de.yaml

add german i18n support

---

layouts/partials/widgets/about.html
layouts/partials/widgets/contact.html

This PR adds a bit more [schema.org](https://schema.org/) tags when it is possible.

Add more schema tags

---

exampleSite/config.toml

Update example config.toml to reflect recent changes of the portrait image display in /layouts/partials/widgets/about.html.

Fix portrait image not display on the home page (index.html)

---

data/sri.toml
layouts/partials/footer.html
layouts/partials/header.html

Move Google Analytics to the header, use async loading, and add autotrack.js

---

layouts/publication/single.html

Fix publication type link error in the multilingual mode. (issue #232)

Fix the issue #232

---

data/i18n/languages.yaml
i18n/pt.yaml

Add support for the Portuguese language.

Portuguese language support

---

data/i18n/languages.yaml
i18n/pl.yaml

Add support for the Polish language.

Polish translation

---

data/i18n/languages.yaml
i18n/it.yaml

To add Italian in hugo-academic

---

data/i18n/languages.yaml
i18n/ko.yaml

I added Korean translation to the theme.

Add Korean translation

---

i18n/zh.yaml

Update Chinese translation

---

exampleSite/content/publication/_index.md
layouts/partials/publication_li_simple_div.html
layouts/section/publication.html

make list displays consistent between home and publication index

---

data/sri.toml
layouts/partials/footer.html

Remove tweenMax and scrollToPlugin, since they weren't used.
Update imagesLoaded & jQuery libraries to newer versions.

Update js libraries

---

exampleSite/content/post/writing-markdown-latex.md

Update the documentation in one post of  `exampleSite` to add the solution to #291 and #149 to be less confusing for new users.

Update documentation to add solutions to unespected Mathjax behaviors

---

layouts/partials/header.html

header: do not output RSS links if disabled

---

i18n/es.yaml
i18n/fr.yaml

Added the missing terms from recent updates of `en.yaml` and translated them to French and Spanish

Updated French and Spanish localizations

---

layouts/partials/header.html

Here a PR to address #355 
I obtain twitter id from params.social.

Add twitter card and Open Graph

---

i18n/vi.yaml

Update the translation and fix semantic errors
None
- Improve translation quality [Tiếng Việt].

Update the translation and fix semantic errors (Vietnamese)

---

data/i18n/languages.yaml
i18n/el.yaml

This PR adds support for greek.

Add support for greek

---

data/i18n/languages.yaml
i18n/id.yaml

Add option to translate the interface to Indonesian language.

Interface Language Bahasa Indonesia

---

i18n/es.yaml
i18n/fr.yaml
layouts/partials/cookie_consent.html

Add the French and Spanish translations for the Cookie consent.

i18n: Update French and Spanish translations

---

exampleSite/config.toml

Fixed the outdated link to the Blackfriday configuration page

Fix link to Blackfriday configuration page

---

layouts/partials/article_metadata.html

Signed-off-by: Prateek Kumar <prateek@prateekkumar.in>
This PR fixes microdata for multiple authors for posts.
Previously multiple authors were not added to microdata.

post: Fix microdata for authors

---

layouts/sitemap.xml

Fixes https://github.com/gcushen/hugo-academic/issues/612 by excluding widgets.

Exclude all widgets from sitemap.xml

---

i18n/it.yaml

just updated the italian strings

update italian translations

---

data/i18n/languages.yaml
i18n/ca.yaml

Allow to use the hugo-academic with Catalan translations.
There is no GUI change
Documentation should be updated to include the Catalan language, i will create a PR for the docs repository

Add catalan translations

---

i18n/es.yaml
i18n/fr.yaml

Just added some translations for fr and en.

Translating from en to fr and es

---

i18n/fr.yaml

Adding some missing terms in the French translation file.
n/a
n/a

French translation updated

---

layouts/project/single.html

Commit 7c2a85c3513fc59b3aa363de9af02bed2adf2f18 forgot to rename `post_format`, `publication_format`, `talk_format` in `layouts/project/single.html`.
Related to #909.

Fix *_format to *_view

---

i18n/zh.yaml

i18n: update Chinese translation

---

data/i18n/languages.yaml
i18n/da.yaml

Translation danish

---

i18n/de.yaml

update translation de

---

i18n/de.yaml

Fixed typo

---

data/i18n/languages.yaml
i18n/ro.yaml

just the file translated in romanian

romanian translation

---

assets/js/academic.js

fix showing search on page refresh - remove query params on search close

---

assets/js/academic-search.js
assets/js/academic.js

switch URL updating strategy from pushState to replaceState

---

exampleSite/config/_default/params.toml
layouts/partials/edit_page.html

Allow to specify the branch of the repository, for the edit button.
https://github.com/sourcethemes/academic-www/pull/8

Allow to specify branch of git repository

---

layouts/partials/navbar.html

Fix navigation bar for translated sites

---

i18n/de.yaml

Add 1 missing translation, correct 1 missing translation, fix 2 translations to me more suitable.

Advanced German translation

---

data/page_sharer.toml

For people's convenience, I have added the template to share on the Xing platform (largest competitor to LinkedIn on the german market).

Add Xing to page_sharer.toml

---

layouts/slides/baseof.html

I believe index.webmanifest is what's being generated

Fix webmanifest link

---

data/page_sharer.toml

Adding Tumblr to page_sharer.toml

add Tumblr to page_sharer.toml

---

exampleSite/config/_default/params.toml

In case you want to collect more address formats

Added address format for German addresses

---

exampleSite/config/_default/params.toml

Add the french address format in `params.toml`

Add  french (France) address format

---

i18n/zh.yaml

I just make some minor adjustments to the Chinese expression.
Before
After

Adjust Chinese translation for minute_read

---

exampleSite/content/authors/admin/_index.md

Fixes #1435. Also removes some trailing spaces, incidentally.
Updates link to point to correct section.

Fixes #1435

---

i18n/ru.yaml

While working on the Ukrainian translation that I commissioned (#1444), my translator reviewed the Russian translation as well and noticed a few typos. This PR corrects those typos.

i18n: Fix typos in Russian translation

---

i18n/pl.yaml

I'm not academia person and may not get these domain names 100% correct but I had to at least translate contact fields and did the rest too
---
---

Add all polish translations

---

data/i18n/languages.yaml
i18n/km.yaml

I would like to add my own language support.

Add Khmer language support

---

data/i18n/languages.yaml
i18n/lv.yaml

i18n: add Latvian language

---

i18n/ko.yaml

update old and missing korean translation.
add 42 missing translations, fix 6 translation for more suitable.

Update korean translation

---

assets/scss/academic/_root.scss

Fix for breakpoint issue #1577

---

data/assets.toml

Updates the mermaid dependency to 8.4.8 from 8.4.4

update mermaid to 8.4.8

---

exampleSite/content/home/skills.md

If this is an enhancement, add a link here to the corresponding pull request on https://github.com/sourcethemes/academic-www or describe the documentation changes necessary.

[chore] fix link to icons in example site

---

i18n/cs.yaml

Updates Czech translation
N/A
N/A

fix: czech translation updated

---

data/i18n/languages.yaml
i18n/so.yaml

This PR adds support for the Somali language.

i18n: add Somali language

---

data/i18n/languages.yaml
i18n/lt.yaml

i18n: add Lithuanian language

---

i18n/nl.yaml

Update NL translations

---

i18n/ar.yaml

I created a new language pack Arabic (ar)
I translated some terms and the rest on the way, but It will be great if the others contribute
related to the:
Add built-in support for RTL languages #1639

New language pack Arabic (ar) - ar.yaml

---

data/i18n/languages.yaml
i18n/ar.yaml

I added the Arabic language to the file - data/languages.yaml
Purpose
related to the:
Add built-in support for RTL languages #1639

I Added the Arabic language to the file - languages.yaml

---

data/i18n/languages.yaml
i18n/fa.yaml

Added i18n/fa.yaml by a native speaker.

Added Farsi language pack.

---

layouts/partials/site_footer_license.html

fix: correct path to copyright license attributes

---

assets/js/academic.js

Fixes incompatibility with site_js.html that is preventing proper initialization of mermaid.
Fixes #1742.

fix: change isDarkTheme to boolean in academic.js

---

exampleSite/static/admin/config.yml

Should this not use the new `media` folder?

Update media folder in cms example configuration

---

assets/scss/academic/_docs.scss

The sidebar in the print is disabled.

Hide sidebar of docs to print

---

i18n/eu.yaml

Add missing eu translations and improve style for better readability.

i18n: add missing eu translations and improve style

---

wowchemy/data/i18n/languages.yaml
wowchemy/i18n/he.yaml

Added Hebrew translation

---

wowchemy/data/i18n/languages.yaml
wowchemy/i18n/nb.yaml

Adding a Norwegian translation in Norwegian bokmål (nb aka nb_NO).

Norwegian translation

---

wowchemy/layouts/partials/marketing/microsoft_clarity.html
wowchemy/layouts/partials/site_head.html

Adding Support for Microsoft Clarity Web Analytics tool

Issue-1923: Add support for Microsoft Clarity

---

wowchemy/layouts/partials/widgets/people.html

This addresses #1941 
A separate update of `people.md` is also needed.

Allow to list people organization in the widget.

---

wowchemy/assets/scss/wowchemy/_widgets.scss

Update .project.card width

---

wowchemy/i18n/he.yaml

Updates Hebrew translation and improves consistency.

Update Hebrew translation

---

wowchemy/i18n/es.yaml
wowchemy/i18n/eu.yaml

This PR updates `eu.yaml` and `es.yaml` translations with the recent changes. Also, updates `es.yaml` formatting by adding spaces to make comparing with `en.yaml` easier.

i18n: update eu and es translations and formatting

---

wowchemy/i18n/es.yaml
wowchemy/i18n/eu.yaml

This PR updates EU and ES translations with the recent changes.

i18n: update EU and ES translations

---

wowchemy/data/address_formats.toml

Add  address format used in Brazil

Add Brazil (pt-br) address format

---

wowchemy/data/i18n/languages.yaml
wowchemy/i18n/fi.yaml

If this is an enhancement, add a link here to the corresponding pull request on https://github.com/sourcethemes/academic-www or describe the documentation changes necessary.

Add Finnish

---

wowchemy/i18n/zh-Hant.yaml

The translation in line 154 is in simplified Chinese. So changing it to traditional Chinese.

Change some simplified Chinese to traditional Chinese in zh-Hant.yaml

---

wowchemy/data/address_formats.toml

This PR adds the Dutch address format to the address format specification file.

Add dutch address format

---

wowchemy/data/address_formats.toml

As mentioned in the title, I added the address format for Canada in English and French.

adding en-ca and fr-ca format

---

wowchemy/i18n/zh-Hant.yaml

- "more" means "更多" instead of "全部"
- fix a simplified character "费" to "費"
- some English translated

Make zh-Hant translation more accurate

---

wowchemy/i18n/id.yaml

Translate to Indonesian Language.
It was perfectly translated. but, better You re-check before You merge with Google translate extensions to make sure about it. Hope this is useful.

i18n: update Indonesian (id)

---

wowchemy/data/fonts/mr_robot.toml

My website stop building with error:
ERROR 2022/01/09 20:55:54 There is a new version of Google Fonts. Learn how to upgrade your font pack at https://wowchemy.com/docs/customization/#custom-font
ERROR 2022/01/09 20:55:54 logged 1 error(s)
Previously this was only a warning.

fix: migrate mr_robot font to Google Font API v2

---

wowchemy/data/i18n/languages.yaml
wowchemy/i18n/mg.yaml

Adding the language pack for Malagasy translation.

pack for Malagasy language

---

starters/academic/content/slides/example/index.md
starters/markdown-slides/content/slides/example/index.md

The old link mentioned does not longer exists, so I changed in to the actual target.

update link with slide pdf export

---

wowchemy/i18n/ja.yaml

I translate some Japanese words.

Translate some Japanese words

---

starters/academic/config/_default/config.yaml
starters/academic/go.mod
starters/blog/config/_default/config.yaml
starters/blog/go.mod
starters/course/config/_default/config.yaml
starters/course/go.mod
starters/documentation/config/_default/config.yaml
starters/documentation/go.mod
starters/markdown-slides/config/_default/config.yaml
starters/markdown-slides/go.mod
starters/minimal/config/_default/config.yaml
starters/minimal/go.mod
starters/notes/config/_default/config.yaml
starters/notes/go.mod
starters/portfolio/config/_default/config.yaml
starters/portfolio/go.mod
starters/research-group/config/_default/config.yaml
starters/research-group/go.mod

…module names in go.mod to correspond to the repo path
Updated module paths as described in #2754
Additionally modified the module name in go.mod files where it deviated from the repo path.
n/a
n/a

updated module paths and modified starter module names 

---

modules/wowchemy/data/i18n/languages.yaml
modules/wowchemy/i18n/bn.yaml

Added translations in Bengali (বাংলা) for a Bengali (Bangladesh, India) language pack.
For each `id`, the original translation in English is preserved as a comment. In some cases, one alternative Bengali translation is also provided.
For `id: minute_read`, an alternative translation is provided to cater for the two interpretations of the `id`. Only one translation should be used for `id: minute_read` depending on the intended meaning -- delete the other one.

Bengali (Bangladesh, India) language pack

---

modules/wowchemy/data/i18n/languages.yaml
modules/wowchemy/data/i18n/rtl.toml
modules/wowchemy/i18n/ms-Arab.yaml
modules/wowchemy/i18n/ms.yaml

Added language pack for Malay in both script.

Lang pack for Malay (Roman & Jawi)

---

docs/en/content/writing-markdown-latex/index.md

Update docs according to the latest changes documented [here](https://gohugo.io/content-management/shortcodes/#tweet).

Update tweet shortcode documentation

---

modules/wowchemy/i18n/fr.yaml

While I'm a French native speaker; I used DeepL to ensure the quality of the translation

with more translation

---

modules/wowchemy/i18n/de.yaml

Update de.yaml, change translation of Thesis to Abschlussarbeit
If this is an enhancement, add a link here to the corresponding pull request on https://github.com/sourcethemes/academic-www or describe the documentation changes necessary.

i18n: update de.yaml to improve translation of Thesis to Abschlussarbeit

---

starters/academic/config/_default/params.yaml
starters/blog/config/_default/params.yaml
starters/course/config/_default/params.yaml
starters/documentation/config/_default/params.yaml
starters/markdown-slides/config/_default/params.yaml
starters/minimal/config/_default/params.yaml
starters/portfolio/config/_default/params.yaml
starters/research-group/config/_default/params.yaml
starters/second-brain/config/_default/params.yaml

Added Google Tag Manager and MS Clarity in the starter files.

add google_tag_manager and microsoft_clarity in starters

---

modules/wowchemy/i18n/ja.yaml

Updated some of untranslated Japanese in i18n yaml.

i18n: improve Japanese (JA) translation

---

modules/wowchemy/i18n/nb.yaml

Some new strings and some small corrections to the Norwegian translation.
When updating my website to the new versions of wowchemy I discovered some new strings had been added, but had not gotten any translation to Norwegian.
So I looked through it and did a new round of translations.

Updating Norwegian translation

---

modules/wowchemy/i18n/vi.yaml

I'm a Vietnamese and I found some issues with the Vietnamese translation in your theme. This PR is to fix these problems.

[i18n] (Fix|Add) Vietnamese translation

---

modules/blox-tailwind/data/languages.yaml
modules/blox-tailwind/i18n/hr.yaml

Added Croatian language pack:
added file:
modules/blox-tailwind/i18n/hr.yaml
modified file:
modules/blox-tailwind/data/languages.yaml

Add Croatian Language Pack

---

modules/blox-tailwind/i18n/de.yaml

Add missing German translations
The current version is missing some of the core translations for German.

chore(i18n): Update de.yaml

---

modules/blox-tailwind/i18n/de.yaml

Add missing translations, that exist in english language file but not in the German

chore(i18n): Add missing German translattions

---

modules/blox-tailwind/i18n/fr.yaml

This commit adds the translation of Experience from English to the French equivalent (plural)

Update French Experience translation 
