HugoBlox/hugo-blox-builder

layouts/partials/header.html

Usage of the Hugo function `default` for specifying the language.

header.html: Use "default" to specify the language.

---

layouts/partials/share.html

The share box is not accessible to screen readers (it does not contain
text). Thus, I excluded it from screen-readers via aria-hidden.

share.html: Apply aria-hidden to share-box

---

layouts/partials/widgets/about.html

Added `safeURL` option (as in [1]) to social icon links to be able to use "non-safe" URIs (`bitcoin:` in my case).
[1] https://github.com/spf13/hugo/blob/0f6c73cf2ef3fa478a635b54652173eefa1f3a17/docs/content/templates/functions.md#safeurl

Added safeURL option to social icon links

---

archetypes/talk.md
exampleSite/content/home/contact.md
exampleSite/content/home/posts.md
exampleSite/content/home/projects.md
exampleSite/content/home/talks.md
exampleSite/content/home/teaching.md
exampleSite/content/talk/example-talk.md

The archetype for talks missed an "event" attribute, which is added
in this commit.
Additionally the exampleSite is updated to contain an example talk.

fixed archetype talk and added example talk to exampleSite

---

exampleSite/content/home/about.md

For some reason, the about widget is displayed at the very bottom on the homepage if weight = 0. Changing weight to 1 will move it to the top.
I'm using Hugo 0.18 on macOS. Not sure if it is a Hugo bug.

Change the weight of about.md from 0 to 1

---

layouts/partials/navbar.html

Commit 59116be74e14884d2fda2b5da3a32bb20174f9b1 has broken smooth scroll to widgets because of missing class specifiers.

Fix broken smooth scroll.

---

layouts/partials/widgets/projects.html

Text link to project_url is not opening in new tab (unlike image link above) for external projects.

Fix a741bc6 (missing card_text target specifier).

---

i18n/zh.yaml

It is a simplified Chinese version of translation. I am not sure whether it would be better to use `zh-Hans` or not. Since you are using `zh` as a sample in the [Getting Started](https://gcushen.github.io/hugo-academic-demo/post/getting-started/) documentation, I guess keeping the same would make things easier for starters.

Add zh localization

---

i18n/fr.yaml

In american english it is common to capitalize the first letter of each
word in a title.
This is not the case in french.

i18n,fr: do not capitalize the first letter of each word

---

layouts/sitemap.xml

We only add this in the sitemap and not in the header.
We can do one or the other but not both. Having this in the sitemap
avoid increasing the size of each page needlessly.
See https://support.google.com/webmasters/answer/2620865
See #67

layout/sitemap: add alternate hreflang links when a page is translated

---

layouts/partials/footer.html

MathJax CDN will shutdown, hence update to cloudflare cdn
See https://www.mathjax.org/cdn-shutting-down/

footer: update MathJax cdn

---

layouts/partials/widgets/about.html

The image property is not set properly. It expects text or url but it
will not look in the background-image CSS property, thus it is not
found.
Fix this by adding an hidden meta element.

about: fix schema tag for the image

---

static/js/hugo-academic.js

This edit ensures that the navbar will collapse when the text of a navbar entry is clicked.  Without this fix, clicking the text itself (instead of the space near the text in the navbar) causes the menu bar to fail to collapse because the event comes from a <span> element instead of the <a> element that contains the <span>.

Fix menu bar collapse on mobile

---

layouts/partials/publication_li_detailed.html
layouts/publication/single.html

Added markdownify filter which allows the use of markdown in abstracts. This addresses #198 and #201.

Add markdown in abstracts

---

archetypes/post.md
archetypes/project.md
archetypes/publication.md
archetypes/talk.md
theme.toml

From Hugo 0.24 date and title must be provided in the archetype file itself, if needed.

Generate title and date explictly

---

layouts/partials/publication_links.html

If `url_project = "project/myprojectA"` in frontmatter, the link should be `/project/myprojectA/` in English lang, and `/zh/project/myprojectA` in Chinese lang.

fix url_project link in multilingual mode

---

layouts/partials/comments.html

In` _internal/disqus.html`, there is already a disqus_thread div: https://github.com/gohugoio/hugo/blob/00b590d7ab4f3021814acceaf74c4eaf64edb226/tpl/tplimpl/template_embedded.go#L168

Remove redundant disqus_thread

---

layouts/partials/css/academic.css
layouts/partials/widgets/projects.html
static/js/hugo-academic.js

This makes the project widget reusable and should resolve #100.
The basic idea is to dynamically create separate click handlers for the filter buttons of the various project widgets by using appropriate scoping of the variable which refers to the relevant project section.

Multiple project widgets

---

layouts/partials/talk_li_detailed.html
layouts/partials/talk_li_simple.html
layouts/talk/single.html

`3:00 PM` can not format `minute` correctly. 
Reference: https://gohugo.io/functions/format/

Fix talk time format

---

archetypes/publication.md
archetypes/talk.md

`projects = [""]` is an array with one element. Thus, even if a publication doesn't belong to any project, the default value `projects = [""]` will always generate a project button, which links to `BASE_URL/project/`. 
Set `projects = []` as default can fix this issue.

Set projects to empty array in archetypes

---

exampleSite/config.toml
layouts/partials/talk_li_detailed.html
layouts/partials/talk_li_simple.html
layouts/talk/single.html

- Added a time_format variable in config.toml (mainly to choose between am/pm or 24h format)
- time_format is used in displaying the time of Talks in lists and single pages
- Also corrected the reference to flippinggodateformat.com (unavailable since the end of 2016) to fuckinggodateformat.com

time_format variable in config used in Talks

---

layouts/partials/widgets/projects.html

Fixes a bug introduced in the fix of #306, where the project filter buttons are shown even when there is only one filter avaliable.
The clause `if and (($page.Params.filter) (gt (len $page.Params.filter) 1))` returns `true` under all circumstances, as does `and ((true) (false))`, due to the parentheses.
To check the length of `filters` only if the parameter `$page.Params.filter` is set, nested `if`-clauses are required, since the templating system does not provide short-circuit evaluation of boolean expressions.

Fix project filter buttons

---

data/sri.toml
exampleSite/config.toml
layouts/partials/footer.html
layouts/partials/header.html
layouts/partials/widgets/contact.html
static/js/hugo-academic.js

This adds an OSM-based map as an alternative to Google Maps to the contact widget. It is activated by providing coordinates, but no gmap api key. Currently two tile sets are provided: The stock OSM tiles which are subject to the [OSM tile usage policy](https://operations.osmfoundation.org/policies/tiles/) and tiles provided by [Mapbox](http://www.mapbox.com) which are based off OSM data as well, but require an api key. The latter is useful for high traffic sites that may violate the OSM tile usage policy.

Provide an OpenStreetMap-based alternative to Google Maps

---

layouts/partials/header.html

This adds an link-rel-hreflang to the page header for every available translation.
This enables modern browsers to automatically choose the right language version of any translated page (without visiting the sitemap).

Add hreflang to page header

---

layouts/publication/single.html

The simple idea behind this PR is that there is no point in showing the abstract header if there is no actual abstract. It therefore makes the abstract optional. Particularly new users who have already some publications might benefit from this. It simplifies the setup of a nice looking site while allowing for adding abstracts later on. 
@gcushen Please take a look.

Making Abstracts Optional

---

layouts/partials/article_metadata.html
layouts/partials/post_li.html

This commit will enable search engines to properly see each blog entry listed on the first page, a small but vital change.

Set the correct MicroData for blog-posts listed on the first page

---

exampleSite/content/home/projects.md
layouts/partials/widgets/projects.html

*project* widget is a very nice feature and is reusable. However, there are still many limitations and inconvenience related to the project widget. See #100, #274, #396.
This PR makes project widget more usable and is compatible with older codes.
If someone wants to reuse project widget, e.g. adding a people section, he can just copy `content/home/projects.md` to `content/home/people.md` and `content/projects/` to `content/people/` and modify modify some frontmatter in markdown files.

Make project widget easier to reuse

---

layouts/partials/navbar.html

When trying to add an entry to the navigation menu, the following error happened if the URL is less than 4 characters, in my case, "#cv"
> error  calling partial: template: partials/navbar.html:63:52: executing "partials/navbar.html" at <slicestr .URL 0 4>: error calling slicestr: slice bounds out of range
this is due to
`{{ if eq "http" (slicestr .URL 0 4) }}`
and can be fixed by checking the length of the URL.
By the way, I was trying to make it
`{{ if and (gt (len .URL) 4) (eq "http" (slicestr .URL 0 4)) }}`
but it seems that short-circuit evaluation is not supported.

fix the error when calling slicestr to slice out-of-range bounds

---

layouts/partials/publication_links.html
layouts/partials/talk_links.html

Fix a bug related to links to `projects` for multi-language sites.
For example, for a Chinese website, the link should be `zh/project/myproject/` not `project/myproject/`.

use relLangURL for project links

---

layouts/partials/header_image.html
layouts/partials/post_li.html
layouts/partials/publication_li_detailed.html
layouts/partials/talk_li_detailed.html

Previous implementation hard-coded an "img/" prefix to the header image URL. This means posts cannot use images from an external source.
This first parses the URL and checks if it has a http/https prefix. If it does, we know it's an absolute URL, so we don't add any prefixes.
Otherwise it's a relative URL, and we append the "img/" prefix as it did before.
none
Note that both local (in `img/` dir) and external images are supported.

Support external header images.

---

layouts/partials/css/academic.css

center social icons when there is more than one line
before:
after:

center social icons when there is more than one line

---

layouts/partials/cookie_consent.html

This changes the partial `cookie_consent.html` so that the cookie consent banner has a more appropriate theme, i.e., so that it agrees with each of the academic themes.

Updated the cookie consent banner so it changes according to the theme

---

layouts/partials/article_metadata.html

Signed-off-by: Prateek Kumar <prateek@prateekkumar.in>
For posts, in the structured data, datePublished and dateModified may be different. Previously both datePublished and dateModified were set to same value `$.Date`. In this commit, these fields are set to `$.Params.Date` and `$.Params.LastMod` respectively.

Fix date published and date modified in structured data

---

layouts/partials/header.html

Signed-off-by: Prateek Kumar <prateek@prateekkumar.in>
Disables Google analytics and autotrack.js when run using `hugo server` command.

Disable Google Analytics in development mode

---

theme.toml

Recent commit 7f744f022bba27cd43dc842e6b82dc34c1ae2537 used `.Site.IsServer`, which is added since hugo 0.38.

Bump minimum version of Hugo to 0.38

---

layouts/project/single.html

- Sort list of publications by Date (as in homepage widget) (previously: was sorted by Title I think)
- Sort list of talks by Time_Start (as in homepage widget) (previously: was sorted by Title I think)
- Fix bug that made publications be duplicated under "talks" when there was no talk in a project

projects: Fix list of publications/talks

---

layouts/partials/header.html

Previously only pages used the abstract parameter to populate the description tag. It was not possible to set the description tag on widget sites.
This change fixes that.

Allow a summary to be specified for widget pages

---

data/assets.toml
exampleSite/config.toml
exampleSite/content/home/hero.md
layouts/partials/article_metadata.html
layouts/partials/css/academic.css
layouts/partials/footer_container.html
layouts/partials/navbar.html
layouts/partials/post_li_simple.html
layouts/partials/publication_li_apa.html
layouts/partials/publication_li_mla.html
layouts/partials/publication_li_simple.html
layouts/partials/share.html
layouts/partials/talk_li_simple.html
layouts/partials/widgets/about.html
layouts/partials/widgets/contact.html
layouts/partials/widgets/posts.html
layouts/partials/widgets/projects.html
layouts/partials/widgets/publications.html
layouts/partials/widgets/talks.html
theme.toml

There are a number of icon changes that need to happen when the theme eventually moves to FA 5. FA 5 isn't currently in cdnjs, but I wanted a Mastodon icon for my website, so I made the necessary changes. I figured I would submit the PR to give @gcushen the option of using FA from FA upstream, or to keep on the back-burner in case cdnjs gets the new version. 
**EDIT**: I hadn't seen #541. Sorry!

Changes needed for FontAwesome 5

---

exampleSite/config.toml
layouts/partials/header.html

If it is set, the 'meta_description' Param now used instead of 'role' to set the description meta tag.
Having just the role in the description meta tag does not make sense for optimizing search results. This approach provides the user the ability to easily set the tag in the config.toml file.

Allow description meta tag to be specified separately from the role.

---

data/assets.toml

Fixes #730 
Update font awesome assets to version 5.4.1. This means users can include the latest icons on their websites.

Update font awesome assets to version 5.4.1

---

assets/js/mathjax-config.js
layouts/partials/footer.html

This allows more strict content security policies. Also uses SRI.

Load MathJax config without eval()

---

i18n/ca.yaml

Fixed catalan typo.
According to Catalan dictionary, plural has two `ss` , not one.
https://dlc.iec.cat/results.asp?txtEntrada=interessos&operEntrada=0

Fixed catalan typo

---

layouts/partials/footer.html
layouts/partials/widgets/hero.html

In multilingual sites, the hero widget and the search box are built with URLs without include the baseUrl and the language prefix. This pull request fixes the problem.
Enable the option "defaultContentLanguageInSubdir" and add a language in exampleSite/config.toml for reproduce the error.

Fix Hero widget and Search for multilingual sites

---

layouts/partials/widgets/experience.html

Dates in the experience widget don't currently right align if the location string is longer than the date string. This changes the widget so the dates are always right aligned.

right align date in experience widget

---

exampleSite/content/home/talks.md
layouts/partials/widgets/pages.html

Upgrade Talk widget by adding three options:
- `order`: ascending or descending order
- `exclude_past`: when true the widget will exclude the "past" talks. 
- `exclude_upcoming`: same but for upcoming talks
As we are dealing with static website, the dates of talks are compared to the `now` function and hence to the last building date.
As explained in `#721`, these options allow to re-use the talks widget: one for the past (descending order), one for the upcoming (ascending order), without having to move or change the talks/files.md. 
If a talk has been given, rebuilding the website will "move" it to the "past" talk without having to move a file and hence changing its URL.
A priori, there is no break in previous implementation (if not set, options are set as default).

Pages widget options: exclude past/future (for talk)

---

layouts/partials/widgets/pages.html

I found the `design.view = 4` setting in the front matter of `content/home/publications.md` doesn't work. This commit will fix this issue.

Fix citation view in publication widget

---

layouts/partials/widgets/pages.html

After the "Offset and Limit" section, `$query` would have length of `$items_count`, which makes `$count` always equal to `$items_count`. The later "if" condition for adding the "see all posts" link will never be met.
The fix is to record the length of `$query` into `$count` before any offset and limit.

Bugfix: missing the "see all posts" link on the posts widgets

---

layouts/partials/widgets/people.html

This issue fixes a bug of people widget which is introduced in v4.2.2.
1. Activate the people widget by changing `exampleSite/content/home/people.md`
2. Run `sh demo.sh` and you'll see
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:4:3: executing "index.html" at <partial "widget_page.html" .>: error calling partial: "/Users/seisman/Gits/academic-homepage/themes/academic/layouts/partials/widget_page.html:29:68": execute of template failed: template: partials/widget_page.html:65:9: executing "partials/widget_page.html" at <partial $widget_path $params>: error calling partial: "/Users/seisman/Gits/academic-homepage/themes/academic/layouts/partials/widgets/people.html:29:68": execute of template failed: template: …

Fix people widget

---

assets/js/academic.js
layouts/partials/header.html

If `highlight_style` is set in the `params.toml`, then the two style sheets aren't in the header. This causes an error, making it impossible to switch between light and dark mode permanently.
The issue was introduced in this commit: https://github.com/gcushen/hugo-academic/commit/34cf1f095700f3623a80c23c31d3e2172f7f7c1d#diff-df235be841d195af9df9944a9e319537

Fix JQuery exception when `day_night=true` and (`highlight=false` or `highlight_style` is set)

---

layouts/partials/page_metadata.html

It seems that this place was not updated after some refactoring. As s result, the list of authors was missing from publication pages for example.
Fixes #1055

Fix #1055: list of authors missing on a publication page

---

archetypes/publication/index.md

Adding default 'publishdate' to 'publication' archetype to allow publications further in the future to be shown by Hugo. Fixes #1023.

Adding default 'publishdate'.

---

data/assets.toml

The goal is to update Highlight.js for adding more language (plaintext for example)
I think there is no need to change documentation because it's just an update

Update the asset CDN for Highligt from 9.12.0 to 9.15.6

---

i18n/de.yaml

All but one messages use the formal "Sie" to address the reader. I adjusted the one case in which informal "du" was used.

i18n: Ensured consistent use of formal German

---

i18n/de.yaml

Changed the German translation of "education" from "Ausbildung" to the more general "Bildung".
In my eyes "Ausbildung" refers to "training" (as in job training) and is less appropriate in academic contexts than "Bildung" (which is also education in the knowledge acquisition sense).
@DominikVogel, do you agree?

Minor change to German translation

---

layouts/partials/page_metadata.html

Social Sharing button's link didn't work as reported in the issue `#1116`. This request is to `Fix #1116 `.

Fixed social sharing button link issue

---

i18n/pt.yaml

Most of the Portuguese translations under the `i18n/pt.yaml` file were still in English. I've just updated by comparing to the original English `en.yaml`. I also compared with the Spanish `es.yaml` file due to both languages similarity.
No GUI changes.
No need.

i18n: Portuguese translation (pt.yaml)

---

i18n/es.yaml
i18n/fr.yaml

For French and Spanish translations:
- translated the few missing tokens
- corrected a few mistakes ("Preprint" = "Preprint" in French, "Prepublicación" in Spanish -- confirmed on Wikipedia)
- improved consistency ("Charlas" for "Talks" in Spanish, for all occurrences)

i18n: Update French and Spanish translations

---

assets/sass/academic/_root.scss

Currently, the gallery fancybox styling styles all fancybox instances, which requires extra CSS every time I want to use it.
This PR isolates the fancybox styling to the gallery shortcode.

isolated fancybox styling to the gallery shortcode

---

layouts/shortcodes/figure.html

This PR adds an option to the figure shortcode to embed the figure into the fancybox lightbox.
To enable, use:
{{< figure src="example.png" lightbox="true" >}}
The lightbox variable being unset and any value other than "true" is equivalent to false.  The caption field is embedded in the lightbox caption.
To change the lightbox group, set `lightbox-group="example"`.  Default group is "figures".
Note, it will make more sense, CSS style wise, for this to merge after #1145.

feat: added lightbox option to figure shortcode

---

layouts/partials/widgets/slider.html

The icon class in the slider widget is constructed using
`"{{ $pack }} {{ $pack }}-{{ . }}"` with double `$pack` prefix and
therefore only works for `fa fa-*` icons.
Example: The github icon in the `fab` icon pack is not supported:
```none
cta_icon_pack = "fab"
cta_icon = "github"
```
Before:
After:
Solution: Conditionally detect `$pack_prefix` as done in the about widget [here](https://github.com/gcushen/hugo-academic/blob/263926cc45ab566f8889e9fd4c4b5f42adfd9f1d/layouts/partials/widgets/about.html#L50)

fix: icon in slider widget only works for fa icon pack

---

assets/js/academic.js

8ddf0ca40643401541d844a97df5542817fea1be introduced a spurious token
that breaks scrolling back to top in HEAD.
This change simply reverts that.

Remove extra token merged by accident.

---

layouts/partials/widgets/accomplishments.html
layouts/partials/widgets/contact.html
layouts/partials/widgets/experience.html
layouts/partials/widgets/featured.html
layouts/partials/widgets/featurette.html
layouts/partials/widgets/pages.html
layouts/partials/widgets/people.html
layouts/partials/widgets/portfolio.html
layouts/partials/widgets/tag_cloud.html

If the portfolio widget page has content defined, blackfriday will
render it as markdown, wrapping text in `<p>` tags.
Wrapping the content in additional paragraph tags will cause the
resulting output to look like the following, which is invalid HTML
```
<p>
<p>First paragraph</p>
<p>Another paragraph</p>
</p>
```
(Paragraphs can't be nested)
To reproduce this in the example site, just add a couple paragraph to the portfolio widget page.

Remove paragraph wrapping portfolio widget content.

---

layouts/partials/page_metadata.html

Address the fact that we are trying to insert markdown to support disqus comment count links even on pages that do not support comments.
Fixes #1192.

Attempt to show comments on relevant page types.

---

layouts/partials/cookie_consent.html
layouts/partials/site_head.html
layouts/partials/site_js.html

There are cases where external script loading is currently [src="https: // ..."], and there are also places where it is [src="// ..."].
ex: https://github.com/gcushen/hugo-academic/blob/64cceae0995ff7ba3f362fa699f0e341b14bbca1/layouts/partials/site_head.html#L130
I think it is better to unify this.

Fix omitted URL scheme

---

layouts/404.html
layouts/partials/docs_sidebar.html

Search query is propagated via the q parameter being added to the query
string when users hit enter.
The only reference to #search-query I found is for styling when dark
theme is enabled. The search widget on the page has the right background
color even when removing the id.
Fixes #1198 (HTML validation issues do the presence of duplicate ids on 404 page.)

Remove search-query id from 404 input.

---

layouts/authors/list.html

Ensure the page DOM tree is well formed even when there are no posts to
list for a given author.

Fix DOM structure of author page when no posts.

---

exampleSite/content/terms.md
layouts/partials/site_footer.html

To comply with regulations in the EU, it is wise to also add more precise legal information (aka "imprint") to a website. Regulation says that a link must be found on every page but as this is rather boring content, you don't want that in your menu. The footer has become a de facto standard to put such links.
The data privacy link is already there so it is only consequent to also add the same functionality for legal information.
This patch will help people to avoid customizing the `site_footer.html` file.

Add support for legal.md in footer

---

exampleSite/config/_default/params.toml
layouts/project/single.html
layouts/publication/single.html
layouts/talk/single.html

This allows to selectively enable comments for projects, publications, and talks.

Allow comments for project, publication, and talk

---

exampleSite/content/privacy.md
exampleSite/content/terms.md

This ensures that editing and commenting is also disabled for those informative pages.

Disable editing and commenting for terms & privacy

---

layouts/partials/site_head.html
layouts/slides/baseof.html

Currently only the main language web manifest is linked for other languages.
This patch makes sure the localized webmanifest file is linked.

fix link href to webmanifest for languages

---

exampleSite/content/home/people.md
layouts/partials/widgets/people.html

People widget could be not working as pointed out in #1360.
This PR fixes multiple bugs :
- People widget was always empty. This is due to a wrong query, looking for `.Params.content.user_groups` for every `authors`. However, the `user_groups` belongs to `content` only for the people widget, not for the authors.
- Fix bug in displaying people interest: if frontmatter was written in toml, it did not work, in yaml it lead to an error (wrong context argument `.` instead of `.Params.interests`)
- Bad `</div>` placement in the `range` loop. This problem appears when multiple `user_groups` are set
This PR also proposes some enhancements:
- Hide `user_groups` if empty (no authors)
- Add an option to display people's organizations (or not (default)).

Fix People widget (+ add option)

---

layouts/talk/single.html

Talk page always display "Event : " even if this field is empty. This happens, for example, if the website hosts the event of the talks.
Example (in french):
This fix simply add an `if` statement in the talk page (file `layouts/talk/single.html`).

Talk page: do not display 'event' if empty

---

layouts/partials/custom_head.html
layouts/partials/custom_js.html

The instructions in the partials file direct users to create a folder "layout" instead of "layouts". It misleads new users who are unfamiliar with the project.

Typo mistake "layout" instead of "layouts" for partials folder.

---

layouts/talk/single.html

remove  braces in address output from talks

remove not needed braces

---

layouts/partials/site_js.html

If "hightlight" was not enabled, the following error appeared in the
console:
Uncaught ReferenceError: code_highlighting is not defined

layouts: fix undefined variable

---

exampleSite/config/_default/params.toml
layouts/partials/comments/commento.html

This change allows users to specify a url instead of having to edit the commento.html when they want to use commento with a self hosted instance. Other users of course do not have to change anything.
You can view the PR for the documentation [here](https://github.com/sourcethemes/academic-www/pull/19)

Add option to use self hosted commento instance

---

layouts/partials/widgets/portfolio.html

The portfolio column sizes do not match other 2-column mode widgets, leading to the left column heading looking a little funny.  Compare to the about, experience, or any other 2-column widget.

made portofolio column sizes consistent with other widgets

---

data/assets.toml
layouts/partials/cookie_consent.html

There was an css and js url listed directly in the code. This is not consistent to the other code, which uses assets.toml. Furthermore now it is easier possible to create an offline site with your admin tool.

Added cookie consent to assets.toml so that an offline site is possible

---

exampleSite/config/_default/params.toml

In fact, France and Germany use the same address format. So, this is a patch to align this behaviour.

Use same address format for Germany and France

---

layouts/partials/widgets/tag_cloud.html

Calculate max value before min since $tags list is mutable to reverse function.
Before:
After:

Fix tag cloud size calculation

---

data/assets.toml

Update highlight.js dependency to 9.18.1, which includes several improvements to the language parsers (e.g., c++, which I care about personally).

Update highlight.js to 9.18.1

---

exampleSite/content/home/featured.md
layouts/partials/widgets/featured.html

Adds an option to view "See all" in the featured widget. This links to the archive of *all* publications/pages.
This was requested in #1104 and was closed. 
I wanted this feature too so have implemented it myself, then thought others might want it too.
It does not change any default behaviour, it just adds an extra option. 
The idea of this is when one wants to only display "featured publications" on the homepage but not "recent publications", but still have a clear link from the homepage to all publications.
It is currently possible to manually include such a link as an alert (as suggested in https://github.com/gcushen/hugo-academic/issues/1104#issuecomment-495993127), but I think the display proposed here is nicer. 
When link_to_more is set to "true" in the featured widget, it displays …

Adding link from featured to archive page of all publications

---

layouts/shortcodes/figure.html

Figures used in a technical articles shall have an ID in order to be able to create an anchor link (like headings in native HUGO). See https://gohugo.io/content-management/cross-references/
For a figure:
```
{{< figure src="image.jpg" title="A caption" numbered="true" lightbox="true" >}}
```
you should be a able to do the following in markdown text:
```
This is some awesome text. For more please see [the awesome figure]({{< relref "#a-caption" >}}
```
https://github.com/sourcethemes/academic-www/pull/20

feat: add id to figures to make them linkable.

---

layouts/partials/widget_page.html

It looks like 8d25dbc61fb5d81d2c7be50f43baae4b78ae6476 introduced the following bug that I ran into when I tried to update my site to the latest master:
```
Error: add site dependencies: load resources: loading templates: "/Users/marpaia/git/website/themes/academic/layouts/partials/widget_page.html:21:1": parse failed: template: partials/widget_page.html:21: unterminated quoted string
```
This is also the bug described in #1618

Fix parse error when loading widget_page.html

---

layouts/publication/single.html

It was using the wrong syntax which tripped up Hugo 71.1

Fix if statement in publications/single.html

---

layouts/partials/li_card.html
layouts/partials/li_compact.html
layouts/partials/navbar.html

- Added an `alt` string to `li_card.html` and `li_compact.html` using `{{ $item.Title }}`
- Added an `aria-label` to the search icon using `{{ i18n "search" }}`
- Improve accessibility score for Google Lighthouse metrics (https://developers.google.com/web/fundamentals/accessibility)
- Related to #1592
e.g., 
n/a

Accessibility alts and labels

---

assets/scss/academic/_dark.scss
assets/scss/academic/_root.scss

I believe this small piece of the CSS is in error (at least, I hope it is!). The current CSS background color I believe is overridden by highlightjs, so you would only notice it if not using highlightjs. In this case, I think the better default background color is to match the background color set in the CSS just below this one.
Before:
```
pre,
code {
font-family: $sta-font-mono, monospace;
color: #c7254e;
background-color: #f9f2f4; <-- this is pink!
}
pre {
margin: 0 0 1rem 0;
background-color: rgb(248, 248, 248); /* Match default highlight theme. */
border-color: rgb(248, 248, 248);
font-size: 0.7rem;
border-radius: 4px;
}
```
After:
```
pre,
code {
font-family: $sta-font-mono, monospace;
color: #c7254e;
/* Match default highlight theme. */
background-color: #f8f8f8; <-- this is gray
} …
```

edit background color for pre, code in CSS

---

layouts/partials/site_head.html

Fixes #1714. Note that this PR should not break sites that use the legacy API.
The section about Google font (https://sourcethemes.com/academic/docs/customization/#custom-font) is no longer valid. If you agree with this PR, I will work on the documentation.

feature : allow for Google Fonts CSS API v2

---

i18n/es.yaml

Adds a number of missing `es` (Spanish) translations along with section comments to the `es.yml` file.
Specific strings added:
* `theme_light`
* `theme_dark`
* `theme_auto`
* `edit_page`
* `slides`
**Before:** Note missing translations
```sh
$ hugo server --disableFastRender --i18n-warnings
Building sites … 
i18n|MISSING_TRANSLATION|es|theme_light
i18n|MISSING_TRANSLATION|es|theme_dark
i18n|MISSING_TRANSLATION|es|theme_auto
i18n|MISSING_TRANSLATION|es|edit_page
i18n|MISSING_TRANSLATION|es|slides
...
```
**After:** 😎
```sh
$ hugo server --disableFastRender --i18n-warnings
| EN | ES
-------------------+----+-----
Pages            | 80 | 80
Paginator pages  |  0 |  0
Non-page files   | 22 | 22
Static files     |  5 |  5
...
```

Add missing Spanish translations

---

layouts/shortcodes/figure.html

Fixes #1620 
The current figure shortcode implementation tries to resize "image" resources and for others it just creates an <img> link.
The problem is, Hugo returns SVG for .Page.Resources.ByType "image", but does not support Fit. However, I fixed it for my site by additionally checking if .MediaType.SubType is equal to svg and skipping .Fit for those.

fix: SVG images break figure shortcode.

---

wowchemy/assets/js/academic.js

Since June 1, 2020, the Mapbox classic styles are deprecated and may be removed in the future.
This change updates the Leaflet code to use the currently supported Mapbox style API according to the official documentation at https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/
Here is the relevant excerpt from the Mapbox documentation:
> Which classic styles are being deprecated?
> 
> All Mapbox classic styles will be deprecated. The following is a list of the Mapbox-maintained classic styles that are not receiving data updates and cannot be requested by new applications after June 1, 2020:
> 
>     mapbox.streets
>     mapbox.light
>     mapbox.dark
>     mapbox.streets-satellite
>     mapbox.outdoors
>     mapbox.run-bike-hike
>     mapbox.streets-basic
> …

Update Mapbox API (following classic style deprecation)

---

netlify-cms-academic/static/admin/index.html

Currently, the admin page of my site shows up in Google search results. Adding the noindex tag stops Google from indexing the page.
Searching for certain queries can find a lot of other sites built with Academic that have their admin page indexed on Google.

Stop Netlify CMS from showing up in Google search results

---

.github/contributing.md

Replaces spectrum with discord, as I believe discord is the prefered chat over spectrum.
Also, updates theme's name.

Replaces chat link on contributing instructions

---

wowchemy/layouts/partials/site_footer.html

Consistency. 
(i think) @gcushen introduced config controlled "power up"s in my PR here: https://github.com/wowchemy/wowchemy-hugo-modules/pull/1852
This PR just simply allows control of the power up to be handled in config and uses an identical control mechanism to the code @gcushen used in the previously mentioned PR.
none
None -- I've only seen power ups documented in Patreon.

feat: add additional power_ups option for sponsors

---

wowchemy/assets/scss/wowchemy/_footer.scss
wowchemy/layouts/partials/site_footer_license.html

The current CC icons (when activated) in the page footer, e.g.
- `<img src="https://search.creativecommons.org/static/img/cc_icon.svg" alt="CC icon">`
result in 404 errors.
[Creative Commons Site](https://creativecommons.org/about/downloads/) suggests something like
- `<img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="CC icon">`
But it seems, we can get the CC icons from the fab icon pack, which
seems even better.
Fixes #1931

Use Font Awesome for CC icons in page footer

---

wowchemy/layouts/partials/widgets/people.html

Commit 97606bf added support for `show_organizations` in the people widget. The original author forgot to add the definition of this variable at top of the widget, leading to hugo not being able to build the site because the variable was not initialized.
This commit adds a definition for `show_organizations` at the top of the widget to fix the build error.
As described in commit 97606bf, you can set the value of `show_organizations` in the people widget's `design` section. See an example config at [this page](https://wowchemy.com/docs/page-builder/#people) and add `show_organizations: true` at the end of it.

Add definition for $show_organizations

---

wowchemy/layouts/partials/widgets/people.html

Previously suggested this in https://github.com/wowchemy/wowchemy-hugo-modules/issues/1580.
A similar option has recently been implemented for `$show_organizations`. Seems reasonable to treat all of these as options that can be switched on and off.
Implements #1580

Option to suppress users' roles in people widget

---

wowchemy/layouts/partials/site_head.html

When running `hugo server -e production`, the CSS file wasn't getting fingerprinted. (Note that this issue doesn't affect Netlify deploys because Netlify automatically fingerprint it themselves).
Fixed by replacing the syntax of the if statement with the syntax used in line 148.

Fix CSS fingerprinting

---

wowchemy/assets/scss/wowchemy/_root.scss

The vw units include the scrollbar as part of the viewport width, as explained here: [https://stackoverflow.com/questions/29551606/why-does-vw-include-the-scrollbar-as-part-of-the-viewport](https://stackoverflow.com/questions/29551606/why-does-vw-include-the-scrollbar-as-part-of-the-viewport). This means that when the scrollbar is shown, 100vw is slightly wider than the actual width. This is what caused #1976. 
While the issue was technically fixed in 58c7dd7, it only hid the horizontal scrollbar. As can be seen in the screenshot, elements still overflow horizontally by a small amount and get cut off.

Fix horizontal overflow

---

wowchemy/layouts/partials/functions/get_social_link.html
wowchemy/layouts/partials/functions/parse_social_link.html
wowchemy/layouts/partials/navbar.html

This PR makes it easy to add tooltips to menu (navbar) items.
By adding new parameters to `menu.toml`, tooltips can be easily added to any non-dropdown menu items.
Example:
```ini
[[main]]
id = "someID"
name = "someName"
url = "some/URL/" # Link URL.
weight = 10
[main.params]
tooltip = "tooltipName" # Add tooltip to menu item. Not supported for dropdown items.
tooltip_placement = "bottom" # Tooltip placement. Pick bottom, left or right. Defaults to bottom.
```
This PR is only supported by Hugo v0.79 or newer.
**Changed files:**
wowchemy/layouts/partials/navbar.html

Add option to show existing social links in navbar

---

wowchemy/i18n/de.yaml

During the build, I get warnings for missing German translations for theme switching. This should fix this.
```
Start building sites … 
i18n|MISSING_TRANSLATION|de|theme_selector
i18n|MISSING_TRANSLATION|de|theme_light
i18n|MISSING_TRANSLATION|de|theme_dark
i18n|MISSING_TRANSLATION|de|theme_auto
```

Add missing translations for theme switching

---

wowchemy/layouts/partials/site_head.html
wowchemy/layouts/slides/baseof.html

Fixes: #2055
The default behavior is unchanged since the templates have the following
section in config/_default/config.toml.
```
[outputs]
home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
section = [ "HTML", "RSS" ]
```

fix: don't put the tag when WebAppManifest is not enabled

---

wowchemy/layouts/partials/site_head.html

Fix size of the `apple-touch-icon`, according to https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/#app-icon-sizes (should be 180x180 instead of 192x192).
Note that Android uses the 192x192 size defined in the [`index.webmanifest`](https://github.com/wowchemy/wowchemy-hugo-modules/blob/e47738df5972e217ca7cd333018f07732a55d4c6/wowchemy/layouts/index.webmanifest#L9).

feat: reduce `apple-touch-icon` size

---

wowchemy/data/address_formats.toml

Display addresses in Israel correctly. None of the other formats defined in address_formats.toml are suitable.

Added Israel address format

---

wowchemy/data/address_formats.toml

Adding Finnish address format into contact widget. Hasn't yet been added.
To use: go to `params.toml` in config folder.
Change `address_format = "en-us"` into `address_format = "fi"`

Add Finnish address

---

wowchemy/layouts/partials/comments.html

After updating to Wowchemy 5.0.0 comments are never loaded even though the `engine` configuration has been replaced with `provider` in `params.toml`. Server startup fails with:
```
The 'disqus' comment provider was not found.
```
There seems to be a regression after refactoring. The template is never appended with the `.html` postfix.

fix: comment provider never found

---

wowchemy/data/fonts/rose.toml

Below warning was showing in the terminal. Fixed it
`WARN 2021/03/11 15:49:52 There is a new version of Google Fonts. Learn how to upgrade your font pack at https://wowchemy.com/docs/customization/#custom-font`

Remove warning about font

---

wowchemy/layouts/partials/site_footer.html

There is an empty `p` tag in the site footer when there is no site copyright string since the `with` block is inside of the `p` tag. I moved the `with` block out of the `p` tag so that the tag doesn't appear when there is no copyright.

Prevent empty p tag in site footer when there is no copyright

---

wowchemy/layouts/partials/navbar.html

(I'm very new to web development.)
An HTML validator found that the `aria-controls` attribute of the navbar toggle button doesn't point to an element in the document. It's set to `navbar`, while the navbar IDs are `navbar-main` and `navbar-content`. I changed it to `navbar-content`.

Fix nonexistent navbar button aria-controls ID

---

wowchemy/layouts/partials/site_head.html

Bing also supports site verification via HTML meta tags
Bing also supports site verification for SEO optimization and the site ranking is also used for other search providers such as DuckDuckGo.
Analog to the google or baidu site verification one can then also add this to `params.toml`: 
```
[marketing]
bing_site_verification = "BING_TOKEN"
```

feat: support Params.marketing.bing_site_verification

---

wowchemy-cms/functions/parse.html

**[BUGFIX]** Editorial workflow mode for CMS is not enabled after adding 'publish_mode: editorial_workflow' in params.yaml.
This is because _publish_mode_ entry (which should be a top level entry) is added under _backend_ entry in config.yaml.

Fix editorial_workflow mode for Netlify-CMS

---

wowchemy/layouts/partials/site_footer.html

Fixes 2282, where Privacy link is shown when a tag name "Privacy" exists, even if "Privacy.md" is deleted.

Workaround Hugo bug with GetPages fetching page from a different path to that specified

---

wowchemy/data/assets.toml
wowchemy/layouts/partials/site_js.html

Previously it was fixed to load styles from cdnjs, now it allows custom loading address.
In fact, jsDelivr is the only one available public global CDN in Mainland China.
https://www.jsdelivr.com/network#china

Add data option for customizing loading address of highlight.js language styles.

---

wowchemy/i18n/ca.yaml
wowchemy/i18n/en.yaml
wowchemy/i18n/es.yaml
wowchemy/layouts/partials/widgets/contact.html

[Encouraged by @gcushen](https://github.com/wowchemy/wowchemy-hugo-modules/pull/2377#issuecomment-884489208), this PR adds the possibility of adding an optional custom success page, as documented [here](https://docs.netlify.com/forms/setup/#success-messages), and optional file uploads, as documented [here](https://docs.netlify.com/forms/setup/#file-uploads), to Netlify forms, by adding this to the `contact` widget:
```
form:
provider: netlify    
netlify:
captcha: true
success_page: /thank-you
file_uploads: true
```
An example of a _Thank you_ page could be this, showing a Wowchemy-styled _Go back_ button:
```
---
title: "THANK YOU!"
reading_time: false  # Show estimated reading time?
share: false  # Show social sharing links?
profile: false  # Show author profile?
commentable: false  # …
```

Improved Netlify Forms

---

wowchemy/layouts/shortcodes/table.html

Resolves #2392 
Add support for
```html
{{< table src="cars.csv" header=true caption="Table 1"  delimiter=";" >}}
```
| Tag | Default| Alternative|
|--|--|-|
|src| Name of a file in the page dir|A direct remote URL to csv|
|header|true| false won't let the row 0 to be header|
|delimiter|,| ;,/,\t etc.|

feat: add shortcode to render a CSV as a table

---

wowchemy/layouts/partials/page_links.html

This PR removes unwanted spaces in custom links, before and after the `name` (the icon already has the `mr-1` class).
```
<a class="btn btn-outline-primary btn-page-header" href="/recursos-fisica-quimica/apuntes/2bach/quimica/redox/redox-ejercicios.pdf">
<i class="fas fa-pencil-ruler mr-1"></i>
" Ejercicios "
</a>
```
```
<a class="btn btn-outline-primary btn-page-header" href="/recursos-fisica-quimica/apuntes/2bach/quimica/redox/redox-ejercicios.pdf">
<i class="fas fa-pencil-ruler mr-1"></i>
"Ejercicios"
</a>
```

Remove unwanted spaces in custom page links

---

wowchemy/layouts/partials/page_header.html

Although the max width is already supplied on the div, supplying these
parameters on the image tag prevents a CSS layout shift when the browser
determines the actual dimensions of the image.
This should not change the actual rendering of any images, so should have no documentation impacts.

Add width and height to header/featured image

---

wowchemy/layouts/_default/sitemap.xml
wowchemy/layouts/partials/site_head.html

Setting the private attribute on pages/posts prevents them from
showing up in Wowchemy search. These pages/posts still appear in
search engines, though. This change instructs search engines to ignore
pages/posts set to private.
Fixes #2444
This requires documentation updates as it changes the behavior of the private parameter. I'd propose an MR for this but I can't find the docs on GitHub and there's no edit button on the docs site.

Don't index private pages

---

wowchemy/data/fonts/classic.toml

Small update to fix an error I encountered re: Google fonts on Classic font set. Without this change Hugo raises the following ERROR when font is set to "classic" in params.yaml.
```
There is a new version of Google Fonts. Learn how to upgrade your font pack at https://wowchemy.com/docs/customization/#custom-font
Error: Error building site: logged 1 error(s)
``` 
The Classic font set has not been updated to match the new format required for Google fonts. Attempting to build a site locally or on Netlify now raises an error (noted above) when building. I have refactored the CSS code to fix this error.

Refactor Classic Font Set Google Fonts Syntax

---

wowchemy/data/assets.toml

This commit is mainly meant to complete #2351, to improve wowchemy sites' accessibility in China.
The reason why jsDelivr is the only choice in China has been discussed, so I will just skip this part.
As Cloudflare is also a sponsor of jsDelivr, as well as other famous CDN providers, this move should not harm the performance of people overseas from accessing wowchemy sites. Which sounds ideal to me.
---
In this commit, I also have bumped the minor version of `js.highlight` and `js.instantsearch`. All of these changes had been fully tested on my side.
---
Update all of the SRI to sha-512 format. Which should have no impact at all.

Eliminate `cdnjs.cloudflare.com`; Update all SRI

---

wowchemy/layouts/partials/widgets/about.avatar.html
wowchemy/layouts/partials/widgets/about.html

In CJK languages, it is natural to mark the pronunciation above the text.
Thanks for your suggestions, I added a specific structure instead of modifying content. So now this will not influence the SEO and so on.
If you specific the `anno`, it will render `<ruby></ruby>`. If you leave it blank, it doesn't cause side effects.
```yaml
title: 张三
anno: Zhang San
superuser: true
role: Professor of Artificial Intelligence
organizations:
- name: Stanford University
url: https://www.stanford.edu/
bio: My research interests include distributed robotics, mobile computing and programmable matter.
interests:
- Artificial Intelligence
- Computational Linguistics
- Information Retrieval
education:
courses:
- course: PhD in Artificial Intelligence
institution: Stanford University
year: 2012
- course: …
```

Show name pronunciation in About widgets

---

wowchemy/layouts/slides/baseof.html

Signed-off-by: IceCodeNew <32576256+IceCodeNew@users.noreply.github.com>
This commit is meant to complete #2512, I managed to completely remove the needs of loading scripts from Cloudflare by these two changes.
Not sure the root of the problem, but when I was testing my site, the script failed to load from Cloudflare under some circumstance (the debug info shows that's the CORS problem).
That's basically why I am so actively hunting and eliminating the scripts that loaded from cdnjs.cloudflare.com. And I do think proposing such a change will not affect others in bad means.

Convert Slides from `cdnjs.cloudflare.com` to JSDelivr CDN

---

wowchemy/assets/js/wowchemy-slides.js
wowchemy/layouts/slides/baseof.html

Following [this comment from Geo](https://github.com/wowchemy/wowchemy-hugo-themes/pull/2513#issuecomment-979463308), this PR updates reveal.js to the [latest version](https://github.com/hakimel/reveal.js/releases/tag/4.2.1), so now we can use [MathJax 3 as the math plugin](https://revealjs.com/math/#mathjax-3-4.2.0).

Update reveal.js from 4.1.0 to 4.2.1 with MathJax 3 integration

---

wowchemy/layouts/partials/site_footer_license.html

Fixes issue with license configuration under `footer` in `params.yml` being ignored.
Right now to work around this issue something like:
```
footer:
copyright:
notice: >-
Except as otherwise noted, this work is licensed under {license}, and code
samples are licensed under the MIT License.
license:
enable: true
copyright:
license:
allow_derivatives: true
share_alike: false
allow_commercial: true
```
is needed in `params.yml`
While the following should work:
```
footer:
copyright:
notice: >-
Except as otherwise noted, this work is licensed under {license}, and code
samples are licensed under the MIT License.
license:
enable: true
allow_derivatives: true
share_alike: false
allow_commercial: true
```

Gets license configuration from `footer.copyright.license`

---

wowchemy/layouts/partials/site_head.html

Currently, PostCSS can optionally be run on the main CSS bundle. This change allows PostCSS to also be run on the vendor CSS. This can greatly reduce the size of the vendor CSS bundle when combined with PurgeCSS since most of the Font Awesome CSS is unused.
No documentation changes are necessary as far as I know.

Run PostCSS on vendor CSS

---

wowchemy/layouts/authors/list.html
wowchemy/layouts/index.json
wowchemy/layouts/partials/site_head.html
wowchemy/layouts/partials/widget_page.html
wowchemy/layouts/partials/widgets/people.html
wowchemy/layouts/publication/single.html

Based on Hugo documentation (https://gohugo.io/variables/files/) and deprecation notice from HUGO > `v0.92.0`.
It seems the solution is to replace the use of `.Path`with `.File.Path`.
Fix #2592

feat: address Hugo v0.92 notice RE changing behaviour of .Path

---

wowchemy/layouts/project/single.html

fix: post list duplicated on project page

---

starters/academic/config/_default/params.yaml

Github has changed from using master -> main as the default branch name for new repos. So when netlify creates a new repo based on this template, the default branch is named 'main' instead of 'master'.
Leaving this config param as 'master' will result in a credentials error whenever a user tries to login using the /admin page. Renaming this to 'main' fixes the error.
If this is an enhancement, add a link here to the corresponding pull request on https://github.com/sourcethemes/academic-www or …

Rename cms branch param from master

---

wowchemy/layouts/partials/widgets/slider.html

Added media_size option analagous to image_size in homepage backgrounds and fix stale reference to overlay_img.
Adds customizability to slider widget and fixes error.
Enhances https://wowchemy.com/docs/widget/slider/
Add media_size option analagous to image_size in https://wowchemy.com/docs/getting-started/page-builder/#background
"#  Options are `cover` (default), `contain`, or `actual` size."

Add Slider background fit option to cover or contain image

---

modules/wowchemy/assets/js/wowchemy-slides.js
modules/wowchemy/data/assets.toml

This is an improved fix for improperly rendering mermaid diagrams in Reveal slides if included beyond the 3rd slide.
It also includes update to latest version of mermaid.
**Please note the patch has not tested**
As it's been a while since I setup a wowchemy dev environment. With no clear instruction or easy path to do so, the hassle is too great for me for such a simple and useful patch.  So I would rather at least the community know of this fix and incorporate it if someone can easily test it.
The discussion on this fix from the Reveal repo can be found here:
https://github.com/hakimel/reveal.js/issues/2863#issuecomment-1107444425
I hope it works and you all find it useful
Many thanks for the great effort

improved fix for mermaid diagrams in reveal slides

---

modules/wowchemy/layouts/shortcodes/audio.html
modules/wowchemy/layouts/shortcodes/callout.html
modules/wowchemy/layouts/shortcodes/chart.html
modules/wowchemy/layouts/shortcodes/cite.html
modules/wowchemy/layouts/shortcodes/cta.html
modules/wowchemy/layouts/shortcodes/emoji_list.html
modules/wowchemy/layouts/shortcodes/figure.html
modules/wowchemy/layouts/shortcodes/gallery.html
modules/wowchemy/layouts/shortcodes/gdocs.html
modules/wowchemy/layouts/shortcodes/hl.html
modules/wowchemy/layouts/shortcodes/icon.html
modules/wowchemy/layouts/shortcodes/list_categories.html
modules/wowchemy/layouts/shortcodes/list_children.html
modules/wowchemy/layouts/shortcodes/list_tags.html
modules/wowchemy/layouts/shortcodes/math.html
modules/wowchemy/layouts/shortcodes/mention.html
modules/wowchemy/layouts/shortcodes/spoiler.html
modules/wowchemy/layouts/shortcodes/staticref.html
modules/wowchemy/layouts/shortcodes/table.html
modules/wowchemy/layouts/shortcodes/toc.html
modules/wowchemy/layouts/shortcodes/video.html

Add shortcode parametrs documentation in the html files.
Add the description of shortcode parameters at the top of each file, in order to have a more immediate view of all the options availables. The format is inspired by Python docstrings.
The change should be non-breaking, since only comments are added in the file, while the code is untouched.

Add docs to shortcodes

---

modules/wowchemy/layouts/partials/comments/giscus.html
starters/academic/config/_default/params.yaml
starters/blog/config/_default/params.yaml
starters/course/config/_default/params.yaml
starters/documentation/config/_default/params.yaml
starters/minimal/config/_default/params.yaml
starters/notes/config/_default/params.yaml
starters/portfolio/config/_default/params.yaml
starters/research-group/config/_default/params.yaml

Fixes #2826. I added `giscus.html` to `modules/wowchemy/layouts/partials/comments` to enable Giscus. This solution is adapted from the one provided by @zyrikby in [his article](https://zhauniarovich.com/post/2021/2021-06-giscus/), which was based on an older version of Wowchemy starters. 
To enable giscus, the user needs to 
- Set up a public repository for storing comments
- Install Giscus and allow it to access the public repo for storing comments
- Decide values of Giscus parameters to use in `params.yaml` with the assistance of [Giscus webpage](https://giscus.app). 
The steps above (with more details) should be mentioned on the [documentation page](https://wowchemy.com/docs/hugo-tutorials/comments/) about adding comments, but I was not able to find the corresponding `md` file to edit. …

Implemented Giscus commenting module and modified params.yaml for all starters

---

modules/wowchemy/layouts/partials/cookie_consent.html

Fixes #2282. Although the issue with the invalid Privacy link was reported for the site footer, it also exists in the cookie consent popup as I observed earlier in https://github.com/wowchemy/wowchemy-hugo-themes/issues/2282#issuecomment-1128348907.
The response from the Hugo team with respect to the issue (https://github.com/gohugoio/hugo/issues/8494) is that `.GetPage` and not `site.GetPage` should be used in this context. Hugo does not see it as a problem they need to fix.

Fixed the Privacy link (issue: 2282)

---

modules/wowchemy/layouts/partials/functions/parse_theme.html

Based on the suggestion at https://discord.com/channels/722225264733716590/1024935456313450506/1025050134083543152, this PR makes the warning messages for missing theme specifications more specific.
As an example, the warning is as follows.
```
Theme `forest` not found at `data/themes/forest.toml`
```
As the dark specification in the `forest` theme is missing, this PR will change it to the following.
```
Dark specification for theme `forest` not found at `data/themes/forest.toml`, falling back to dark specification from the `minimal` theme.
```
A similar message will appear if the theme is missing its light specification, for example:
```
Light specification for theme `dark` not found at `data/themes/dark.toml`, falling back to light specification from the `minimal` theme.
```

Updated theme warning messages to be more precise.

---

modules/wowchemy/layouts/partials/site_head.html
modules/wowchemy/layouts/partials/site_js.html

Despite commit acd74954b5dd0a10f683744d11635bb1b1b76076 mentioning that the custom.html is still supported for now, I don't think it's being picked up at the moment. This PR resolves this issue.

fix: legacy support for custom_js/custom_head

---

modules/wowchemy/assets/js/wowchemy.js

The addClass call must be called with class name only instead of '.table' as class name.
Previously this lead to undesirable behavior because markdown tables would be rendered without the proper CSS classes (see screenshots below).
Since I only noticed this problem just now, I did not create an issue so far.
Old behavior:
New behavior:

Fix table class name in fixHugoOutput

---

modules/wowchemy/layouts/partials/blocks/about.avatar.html
modules/wowchemy/layouts/partials/blocks/accomplishments.html
modules/wowchemy/layouts/partials/blocks/collection.html
modules/wowchemy/layouts/partials/blocks/contact.html
modules/wowchemy/layouts/partials/blocks/experience.html
modules/wowchemy/layouts/partials/blocks/features.html
modules/wowchemy/layouts/partials/blocks/hero.html
modules/wowchemy/layouts/partials/blocks/markdown.html
modules/wowchemy/layouts/partials/blocks/portfolio.html
modules/wowchemy/layouts/partials/blocks/tag_cloud.html

Shortcodes in the new block system do not get access to the correct `.Page` variable (see #2918 ). The problem is the use of `markdownify` function to parse `$block.content.text`, since it actually is an alias to `site.Home.RenderString` since v 0.93.0 (see https://github.com/gohugoio/hugo/issues/9959#issuecomment-1142610699). 
This causes the shortcodes to always get the Homepage as `.Page` variable. The fix is to substitute `markdownify` with `$page.RenderString`, which gives the correct context.
An actual example of this behaviour can be found in [this branch](https://github.com/Agos95/wowchemy-hugo-themes/tree/getCSV-test) (in the `csv` page):
This PR fixes #2918.

Fix Shortcode context for v2 blocks

---

modules/wowchemy/assets/scss/wowchemy/elements/_media.scss

Fix Gallery in Chrome.
This is the gallery in Chrome:
This is the gallery in Firefox:
Overriding a flexbox default setting as described in this [StackOverflow post](https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size). Firefox seems to handle it correctly.
Edit.
I found a [WICG post](https://github.com/WICG/view-transitions/blob/main/debugging_overflow_on_images.md) where they are talking about this issue.

Fix gallery in Chrome

---

modules/wowchemy/layouts/shortcodes/list_children.html

Small fix to the comment of the `last_children` shortcode (the default is to show the summary), as pointed out in #2938.

Fix `last_children` shortcode comment

---

.github/workflows/split-packages.yaml

If this is an enhancement, add a link here to the corresponding pull request on https://github.com/sourcethemes/academic-www or describe the documentation changes necessary.

fix: GitHub deprecated GH Actions Node version

---

modules/wowchemy/layouts/partials/blocks/slider.html
modules/wowchemy/layouts/partials/blocks/v1/slider.html

The slider block shows slide switching controls/indicators even when only one slide is defined. This change makes showing those conditional on the number of defined slides. 
This is related to https://github.com/wowchemy/wowchemy-hugo-themes/issues/2129

Slider block: only show controls/indicators if >1 slides are defined.

---

modules/wowchemy/assets/js/algolia-search.js
modules/wowchemy/assets/js/wowchemy-navigation.js
modules/wowchemy/assets/js/wowchemy-search.js
modules/wowchemy/assets/js/wowchemy.js

Remove some low hanging JQuery fruits

---

modules/wowchemy/layouts/partials/blocks/accomplishments.html
modules/wowchemy/layouts/partials/blocks/experience.html
modules/wowchemy/layouts/partials/blocks/v1/accomplishments.html
modules/wowchemy/layouts/partials/blocks/v1/experience.html

According to the HTML standard, the `width` and `height` attributes of an `img` tag must specify the width/height in pixels *without* a unit. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
This was wrong in these two places.

Remove 'px' from width and height fields

---

modules/blox-bootstrap/layouts/partials/functions/get_address.html

Fix the display of addresses with delimiters.

feat: add support for breaking changes in Hugo v0.120.0 - fix display of addresses

---

modules/blox-bootstrap/layouts/partials/site_js.html

Extend the configuration parameters of docsearch to support facets.
Docsearch has something called 'facets' where you can restrict the results based on record attributes in the indexed results. E.g. if the crawler extracts version information from your pages you can restrict search results to latest. See
https://docsearch.algolia.com/docs/docsearch-v3/#filtering-your-search
Fixes #3022
https://bootstrap.hugoblox.com/hugo-tutorials/search/#docsearch
```yaml
features:
search:
provider: docsearch
docsearch:
app_id: 'PASTE ID'
api_key: 'PASTE KEY'
index_name: 'PASTE INDEX NAME'
search_parameters:
facetFilters: 
- '<ATTRIBUTE-NAME>:<VALUE>'
- '<ATTRIBUTE-NAME>:<VALUE>'
```
If you like to limit the results of your search to specific topics, you can define `facetFilters` based on the attributes …

feat: support facet filters for docsearch

---

modules/blox-plugin-reveal/layouts/slides/baseof.html

Main new feature is [**scroll view**](https://revealjs.com/scroll-view/), which is the new default for mobile view.
I have tested this new version with my own slides and haven't seen any regression/bug.

Update revealjs to its latest version (5.0.4)

---

modules/blox-tailwind/i18n/ms-Arab.yaml

Somehow overlooked the underscore.
This fixed the repo link
Screenshot from old build

Tiny fix ms-Arab.yaml

---

modules/blox-plugin-decap-cms/data/decap_cms_config.yaml

Since the front matter fields `first_name` and `last_name` are used for things like SEO and sorting on the people page by default, it would be reasonable IMO to add them to the CMS so that they don't have to be modified manually outside of CMS.
Since the [Decap CMS section](https://docs.hugoblox.com/getting-started/cms/decap/) does not contain any details on all available fields, it looks to me as if it wouldn't need to be updated.
Please do let me know if any changes are needed before merging. Thanks.

Add first and last name fields to decap_cms_config.yaml

---

modules/blox-seo/layouts/partials/analytics/google_analytics.html

site.GoogleAnalytics is deprecated since Hugo v0.120.0 and would need to be changed to site.Config.Services.GoogleAnalytics.ID, which breaks compatibility with earlier Hugo versions. Thus, omit fetching this configuration variable since it should be set via site.Params.marketing.analytics.google_analytics anyway.
On request of @gcushen via Discord discussion.

Remove fetching of default GA ID via site config

---

modules/blox-bootstrap/i18n/fr.yaml
modules/blox-tailwind/i18n/fr.yaml

There's a typo in the french translation of `published_with`, which appears at the bottom of each page:
The french word is `permettant` and not `permetant`.
This PR fixes this typo :)

fix: typo in french translation

---

modules/blox-bootstrap/layouts/partials/components/feedback.html
modules/blox-tailwind/layouts/partials/components/feedback.html

Some occurrences of the Site.GoogleAnalytics variable that is deprecated since Hugo 0.133 have not been removed in #3137, as mentioned by @rodrigoalcarazdelaosa in that same PR.

Remove remains of deprecated Site.GoogleAnalytics

---

modules/blox-bootstrap/layouts/partials/blocks/portfolio.html
modules/blox-bootstrap/layouts/partials/blocks/v1/portfolio.html

Fix argument ordering

---

modules/blox-tailwind/layouts/partials/site_head.html

We are using Cloudflare Pages to host a website built with Hugo Blox. When updating the CSS, e.g. after adding new Tailwind classes, Cloudflare's cache keeps serving the old version, which breaks the website's layout. This problem can be mitigated by fingerprinting `dist/wc.min.css`.
N/A

Fingerprint dist/wc.min.css to prevent cache issues

---

modules/blox-tailwind/assets/css/components/cards.css

After the upgrade to Tailwind v4, the `cards` have obtained an ugly white shadow in the dark theme. This is due to a change in the behaviour of `shadow-none` which (erroneously?) sets the shadow to white. I've corrected this by setting the shadow to `shadow-transparent` for the dark mode.
Tailwind v3 behavior:
Current tailwind v4 behavior:
Patched tailwind v4:

[FIX] erroneous shadow behind cards in dark theme after tailwind upgrade

---

modules/blox-tailwind/blox/resume-skills/block.html

Fix the vertical alignment issue in the resume skills block, where shorter content sections were centering vertically instead of aligning to the top. 
Add a long enough description to each item under skills 
```
skills:
- name: Technical Skills
items:
- name: Python & PyTorch
description: 'Some description text to consume space demonstrating the column start position unevenness'
percent: 90
icon: python
- name: R
description: 'Some description text to consume space demonstrating the column start position unevenness'
percent: 80
icon: r-project
- name: SQL
description: 'Some description text to consume space demonstrating the column start position unevenness'
percent: 70
percent: 95
icon: code-bracket
- name: Machine Learning
description: ''
percent: 100
icon: chart-bar
- name: Cloud …
```

Fix resume-skills block aligns columns to the top instead of the center.

---

modules/blox-tailwind/blox/resume-languages/block.html

Fix progress bar display in resume-languages block by correcting stroke-dashoffset calculation to show accurate progress. Previously, progress bars displayed the gap segment (remaining progress) starting from the first quadrant, whereas for 80% progress, it should appear in the 4th quadrant, causing the visual representation to appear inverted.
**Before:**
*Progress bars displayed the gap segment (remaining progress) starting from the first quadrant, whereas for 80% progress it should 
appear in the 4th quadrant*
**After:**
*Progress bars now correctly display 80% proficiency as 80% filled*
It is a bugfix; no documentation change is needed.

Fix progress bar display in resume-languages block

---

modules/blox-tailwind/blox/resume-languages/block.html
modules/blox-tailwind/blox/resume-skills/block.html

**NOTE:**  This PR depends on changes from https://github.com/HugoBlox/hugo-blox-builder/pull/3259
Add dynamic columns configuration to the resume-skills block with responsive breakpoints. 
Uses standard design.columns parameter (default 2) that creates a progressive responsive grid layout: 1→2→3→4→5 columns across breakpoints (sm→md→lg→xl→2xl). Replaces fixed 2-column flex layout with CSS Grid for better multi-column control and flexibility.
Ensure setting three columns in `experience.md`:
```
- block: skills
content:
title: Skills & Hobbies
username: admin
design:
show_skill_percentage: false
spacing: "3rem 0 0 0"
columns: 3
```
Add a  third item with several sub-items under skills:
```
skills:
- name: Technical Skills
items:
- name: Python & PyTorch
description: 'Some description text …
```

Dynamic columns in resume-skills block
